---
- hosts: all
  become: true
  vars:
  tasks:
    - name: Create development user
      user:
        name=development
        password=$6$Al5BkSlpAZHBP4DY$yacoRMs8hbtUw6pa/bac4dSQtLTuMjDdFX3/9aUx5KZ.tph/z7sfvwSroh2jixcS7/RpBt8q.23fhiSFbfJL91
        groups=sudo
        append=yes
        createhome=yes
        state=present
        update_password=always

    - name: Update shared folder permissions
      file:
        path: /var/www/unaviamedia
        recurse: yes
        mode: "u=rwX,g=rX,o=rX"
        owner: development
        group: www-data

    - name: Update package caches
      apt: update_cache=yes

    - name: Install miscellaneous tools
      apt: name={{item}} state=latest
      with_items:
        - git
        - vim
        - screen

    - name: Install build tools
      apt: name={{item}} state=latest
      with_items:
        - nginx
        - mysql-server
        - php-fpm
        - php-mysql

    - name: Create necessary symlinks
      file:
        src: /etc/nginx/sites-available/site_conf
        dest: /etc/nginx/sites-enabled/site_conf
        state: link
      notify: nginx reload
